### ISSUE TITLE
Berks Dependency Issue for delivery_rust

### ISSUE THREAD

**Issue by josh-barker** [chef/delivery-cli#10]
Hi,

I tried to use the latest version, but berks threw an error when it tried to pull the artifactory-pro cookbook.

Looking at https://github.com/chef/delivery-cli/blob/master/cookbooks/delivery_rust/Berksfile, it seems that the following cookbooks haven't been published to github.com
- https://github.com/chef-cookbooks/artifactory-pro
- https://github.com/chef-cookbooks/oc-artifactory
- https://github.com/chef-cookbooks/opscode-ci

Am I missing something here?

Cheers

**Comment by thommay** [comment]
@chef/engineering-services looks like we have dependencies on private cookbooks in a public codebase...

**Comment by eeyun** [comment]
@josh-barker a heads up, if you comment out `artifactory-pro`,`oc-artifactory`, and `opscode-ci` from the metadata.rb and Berksfile of delivery-rust you will successfully be able to compile the delivery-cli . It doesn't appear that those cookbooks aren't actually used in the recipes needed to build locally.

**Comment by afiune** [comment]
No more private dependencies! 👍  Closing this in favor of https://github.com/chef/delivery-cli/commit/b747f46872df60da20e5ed59635eb7bc37aee603
