### ISSUE TITLE
Doing a 'make dev' fails during CCR due to missing recipe

### ISSUE THREAD

**Issue by chefsalim** [chef/delivery-cli#11]
Repro'd on a Mac OSX.

1. Clone delivery-cli (master).
2. Follow the instructions in README.md by doing a 'make dev all'

Result:
Chef client run fails with error:

  ================================================================================
  Recipe Compile Error
  ================================================================================

  Chef::Exceptions::RecipeNotFound
  --------------------------------
  could not find recipe _openssl for cookbook delivery_rust

**Comment by afiune** [comment]
This was fixed a long time ago, closing this but thank you for the feedback Salim! ✌
