### ISSUE TITLE
Inconsistent --version output

### ISSUE THREAD

**Issue by stevendanna** [chef/delivery-cli#12]
```
> delivery --version
delivery 0.0.15 (454c3f37819ed508a49c971f38e42267ce8a47de)
> delivery api --version
delivery-api
```

**Comment by afiune** [comment]
@stevendanna I think the reason why this is happening is just because we use `clap` under the hoods to manage our commands and it has the awesome option to version your sub-commands (like `delivery api`) but we are not using it.... I guess it might be confusing for customers though!

**Comment by kbknapp** [comment]
You can use [`AppSettings::GlobalVersion`](http://kbknapp.github.io/clap-rs/clap/enum.AppSettings.html#variant.GlobalVersion) to just use the version of the main command for all subcommands or [`AppSettings::VersionlessSubcommands`](http://kbknapp.github.io/clap-rs/clap/enum.AppSettings.html#variant.VersionlessSubcommands) to remove the `--version` from subcommands entirely

**Comment by afiune** [comment]
I'm starting to work on this. 👍
