### ISSUE TITLE
Acquiring first token not possible non-interactively

### ISSUE THREAD

**Issue by cheeseplus** [chef/delivery-cli#13]
Noticed this while trying to build a demo and there are two possible resolutions and think we should do both:

`delivery token` doesn't accept a password non-interactively so one may try to use `delivery api post get-token` but that also requires a token so it's a chicken-egg problem. The workaround is just using curl raw but it's reasonable to expect `delivery api` to behave similarly to curl.
- add password option to `delivery token`
- allow `delivery api` to work without a token, at least for posting to the get-token endpoint

**Comment by afiune** [comment]
Great feedback, I think we should add this to feedback.chef.io since there is where @mgleasonchef is prioritizing the features to do next! 😄

**Comment by afiune** [comment]
@cheeseplus I am currently working on a solution for this.. The approach will be to have a environment variable that you can set on the terminal called `AUTOMATE_PASSWORD` if this variable is set we won't ask to input the password, additionally you will be able to pass a new flag `--raw` that will print just the raw token and nothing else.

**Ex. Requesting a token without the need of a cli.toml file, or human interaction and raw output**
```
$ AUTOMATE_PASSWORD=secret delivery token -s automate.example.com -e automation -u token --raw
MY_SUPER_DUPER_RAW_TOKEN
```

This will be available on the next chefdk release! ✌

**Comment by afiune** [comment]
In favor of https://github.com/chef/delivery-cli/commit/97c95accff83267355e58c28ac724f7c517c2167
