### ISSUE TITLE
Old data in config.json contaminates future runs

### ISSUE THREAD

**Issue by christinedraper** [chef/delivery-cli#15]
## Description

Array fields in the delivery config.json are merged with saved attribute state from old runs, resulting in unexpected and somewhat random results. 

## Replication case

Use a single build node, so successive runs will be in the same node and workspace.

Start with config.json like this:
```
{
    "version":"2",
    "build_cookbook":{
        "path":".delivery/build-cookbook",
        "name":"build-cookbook"
    },
    "skip_phases":[
        "security",
        "quality",
        "smoke",
        "functional"
    ],
    "build_nodes":{       
    },
    "dependencies":[  
    ],
    "delivery-truck":{
        "publish":{
            "chef_server":true
        },
        "lint": {
            "foodcritic": { 
                "fail_tags": [ "any" ]
            }
        }
    }
}
```
Run a changed cookbook through verify... lint should have `-f any`
Now change the config.json to this:
```
        "lint": {
            "foodcritic": { 
                "fail_tags": [ "correctness", "metadata" ]
            }
        }
```
Run the changed cookbook through... lint has `-f any,correctness,metadata`

Logon to build node, go to the workspace for the phase:
```
cd /var/opt/delivery/workspace/33.33.33.11/test/test/mvt/master/verify/lint
```
Look at the attribute json for the phase in chef/dna.json and it is correct:
{"lint":{"foodcritic":{"fail_tags":["correctness","metadata"]}}
Look at the stored node state in chef/nodes/build-node-test-1 and it has the merged data:
```
          "lint": {
            "foodcritic": {
              "fail_tags": [
                "any",
                "correctness",
                "metadata"
              ]
            }
```
The stored node state between the first and second run would have been:
```
          "lint": {
            "foodcritic": {
              "fail_tags": [
                "any"
              ]
            }
```
which is being merged with the dna.json.  This happens for any array attribute that's being passed through for build recipes to use. It's the defined Chef array merge behavior, but in this case it really isn't what the user wants, and there isn't an obvious workaround.

Seems like either:
1) chef-client should be run with -o rather than -r so node state isnt stored
OR
2) the node state should be cleared before each run

**Comment by afiune** [comment]
We are working on a solution for this @christinedraper .. Thank you so much for your always amazing feedback!! 😄

**Comment by afiune** [comment]
Work started. 👍  This will be fix soon!
