### ISSUE TITLE
Provide option to turn off terminal escape codes (color codes)

### ISSUE THREAD

**Issue by stevendanna** [chef/delivery-cli#16]
Delivery review emits terminal escape codes to provide color in its output.  This is problematic for tools that wish to parse the output of delivery commands. For example, delivery-matrix attempts to strip the escape codes but failed to account for the fact that the underlying library delivery-cli is using will output different output based on the value of TERM.  Thus, the regex doesn't cover all the possible codes that might be emitted for the sgr0 escape code that delivery-cli attempts to send to reset the color.

https://github.com/chef-cookbooks/delivery-cluster/blob/31308903144ece68898233882181d36892e3bdf7/.delivery/build/cookbooks/delivery-matrix/libraries/delivery_duplicate_change_on_pipeline.rb#L95

A `--no-color` option would allow users to bypass such complications altogether.

**Comment by xenolinguist** [comment]
Could it be as easy as checking whether STDOUT is a tty before printing fancy colored stuff?

**Comment by stevendanna** [comment]
> Could it be as easy as checking whether STDOUT is a tty before printing fancy colored stuff?

This is what we do in chef-backend and in chef/knife tooling and it works well enough for most purposes.  There are a few cases where tools communicating over SSH will allocate a pty even though they aren't connected to a terminal just so that sudo works.

**Comment by stevendanna** [comment]
Re `--output-json`: In `knife` we provide different output formatters with json as an option and could so something similar here, that is a much larger feature however.

**Comment by xenolinguist** [comment]
> There are a few cases where tools communicating over SSH will allocate a pty even though they aren't connected to a terminal just so that sudo works.

Very true, which I think lends a little weight to the explicit-machine-readable option.

**Comment by xenolinguist** [comment]
> that is a much larger feature however.

Indeed. Probably ought to be a separate feature request.
