### ISSUE TITLE
delivery cli does not support debug mode

### ISSUE THREAD

**Issue by vinyar** [chef/delivery-cli#17]
Issue:
There are many scenarios where delivery cli just fails with a generic, non-descript error.

Desired resolution:
Provide a debug flag for delivery cli.

Additional benefits:
Debug flag will greatly increase customers' ability to self-service
Debug flag will greatly increase supports' ability to assist customers with troubleshooting delivery related issues.

Example:
```
 delivery token
Chef Delivery
Loading configuration from C:\Users\chef\scott_ssh
Requesting Token
An API Error occured
SAML lookup request returned 404 Not Found
```

Other examples:
Delivery init fails on ssh command to the delivery server, there is no stack trace or reference to what actually failed. The ssh command and git commands have to be ran individually in debug mode to get any actionable output.

@glasschef for more examples

**Comment by sean-horn** [comment]
There is a little extra information if you set the `RUST_LOG=debug` environment variable before running delivery-cli commands.

And on windows `PS C:\Users\Administrator> Set-Item Env:RUST_LOG "debug"`

**Comment by afiune** [comment]
Closing this since as Sean mentioned, the way is a way by setting up the environment variable.
