### ISSUE TITLE
Delivery init without a delivery server just hangs

### ISSUE THREAD

**Issue by tas50** [chef/delivery-cli#21]
If you're not actually setup for Delivery and you delivery init in a cookbook it just hangs forever:

MBP:~/dev/chef-cookbooks/tomcat (master) delivery init
Chef Delivery
Loading configuration from /Users/tsmith/dev/chef-cookbooks/tomcat

...nada...

**Comment by afiune** [comment]
@tas50 Have you tried to use `delivery init --local`? This will just run the initialization process of the project without interacting with the Server...

**Comment by tas50** [comment]
Closing this out now since Delivery is EOL
