### ISSUE TITLE
Replace `--auto-bump` with `--bump [ patch | minor | major ]`

### ISSUE THREAD

**Issue by patcon** [chef/delivery-cli#33]
Auto-bump for `delivery review` is really handy! Would be great if it could handle other version point releases

Thinking that `--auto-bump` flag could be deprecated for a `--bump` flag that could be provided with or without args. Without an arg, it would default to `patch` type, but `minor` and `major` could also be specified.

**Comment by patcon** [comment]
Created ticket here, as it didn't seem possible yet with clap-rs:
https://github.com/kbknapp/clap-rs/issues/892

**Comment by afiune** [comment]
@patcon Thank you so much for your feedback! The `auto-bump` mechanism is meant to be a helper for quick simple changes, but if the change requires a minor or major version bump, the believe the user should be in charge of modifying the `metadata.rb` manually.

I'm closing this issue, but if you feel like this is something we need to code I would encourage you to give this feedback at: https://feedback.chef.io/ where more users can vote for ideas and our Product Team can visualize them and move them to in development. Thank one more time.
