### ISSUE TITLE
Delivery review does not respect cli toml when changing server.

### ISSUE THREAD

**Issue by dreamnite** [chef/delivery-cli#36]
We recently had an edge case where we were transitioning from one automate server to another for workflow. We'll call them "automate-old" and "automate-new" fr simplicity.
With a local project checked out from automate-old originally, I ran "delivery setup" with "--server automate-new" to reset my cli.toml. When I made a test change and ran "delivery review" it instead used the current git "delivery" remote and opened the change on automate-old.

Expected Behavior: Delivery review would note that the git remote did not agree with the cli.toml and repoint it appropriately.

**Comment by afiune** [comment]
Hi @dreamnite 👋  - Thank you for your feedback! I wonder what chefdk version are you using?

**Comment by juliandunn** [comment]
@dreamnite btw, irrespective of what version of ChefDK version you're using, we've decided to stop updating remotes under-the-hood (*unless* you are in FIPS mode, because it's necessary for FIPS to work) because we got a lot of negative feedback that folks don't like us updating remotes.

**Comment by tas50** [comment]
Closing this out now since Delivery is EOL
