### ISSUE TITLE
It would be useful to be able to control the logging level of the chef-client run used during an automate job

### ISSUE THREAD

**Issue by rwdalpe** [chef/delivery-cli#43]
For debugging purposes and whatnot, it could be useful to increase or change the logging level of the chef-client used during an automate job.

However, I haven't been able to find any setting that affects the configuration used during an automate chef-client run. Looking at the delivery cli code, I can see that it uses a static configuration defined at https://github.com/chef/delivery-cli/blob/master/src/delivery/job/workspace.rs#L51

and static command line options defined at https://github.com/chef/delivery-cli/blob/master/src/delivery/job/workspace.rs#L271 to determine options for the chef-client run.

Neither of these exposes any way to affect the logging level, so I believe you're always stuck with the default.

**Comment by tas50** [comment]
Closing this out now since Delivery is EOL
