### ISSUE TITLE
Unable to run delivery init successfully

### ISSUE THREAD

**Issue by adyanthaya17** [chef/delivery-cli#45]
Hi,

I have my workstation installed and configured in my Chef Server which has coookbooks in them. I tried running the delivery set up and created a token. While trying to initialize using 'delivery init' I get:

root@chef-server:/tmp/test_cookbook# delivery init --repo-name test_cookbook  --server 10.X.X.XX --ent delivery-org --org delivery-org --skip-build-cookbook --user admin
Chef Delivery
Creating Delivery project...
  Delivery project named test_cookbook was created.
Setting up the 'delivery' git remote...
  The delivery git remote has been configured to 'ssh://admin@delivery-org@10.X.X.X:8989/delivery-org/delivery-org/test_cookbook'.
Pushing initial git history...
Git command failed!
STDOUT:
STDERR: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I have created the keys and have placed them in the git account that is the public key but unfortunately I didn't find it successful. 

root@chef-server:/tmp/test_cookbook# delivery init --repo-name test_cookbook  --server 10.X.X.X --ent delivery-org --org delivery-org --skip-build-cookbook --user admin --github delivery
Chef Delivery
Github Source Code Provider configuration not found; a Delivery administrator must first configure the link with Github.

Does anyone know why this is happening? It would be a great help. Thank you!

**Comment by tas50** [comment]
Closing this out now since Delivery is EOL
