### ISSUE TITLE
"Invalid argument" for api requests with spaces in data

### ISSUE THREAD

**Issue by edanaher** [chef/delivery-cli#7]
Putting a space inside the JSON (either within a field or simply between fields) results in an "Invalid arguments" error and usage message.

```
$ delivery api put users/edanaher  --data='{"ssh_pub_key":"ssh-rsaabc12345"}'
$ delivery api put users/edanaher  --data='{"ssh_pub_key":"ssh-rsa abc12345"}'
Invalid arguments.
```
Further, using "+" or "%20" (in the hopes that it's a URI-encoding issue) produces a literal "+" or "%20", and further escaping the space also resulted in the error.

Spaces work fine using the API directly; for example the following results in an ssh key with a space in it:

```
curl -H 'chef-delivery-user: edanaher' -H 'chef-delivery-token: [snip]' -i -k -H "content-type: application/json" -X PUT https://delivery/api/v0/e/ooyala/users/edanaher -d '{"ssh_pub_key": "abc 12345"}'
```
So this seems to be pretty clearly a bug in the CLI.

**Comment by cheeseplus** [comment]
Tested this recently and this is fixed.
